name = "mcpe-app"
pages_build_output_dir = "build"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "e8ae4859ab984ec98c6e828ba4a42dc1"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "mcpe-maps"
database_id = "b6f0721d-afd9-4f52-806a-2b967851cb50"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "e8ae4859ab984ec98c6e828ba4a42dc1"

# Preview environment (for PRs and branch deployments)
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "mcpe-maps-dev"
database_id = "7faae035-762c-4ca5-b1c9-5b7b59b97a4e"

[[env.preview.kv_namespaces]]
binding = "CACHE"
id = "e8ae4859ab984ec98c6e828ba4a42dc1"

# Local development - use this when running wrangler pages dev
[[d1_databases]]
binding = "DB"
database_name = "mcpe-maps-dev"
database_id = "7faae035-762c-4ca5-b1c9-5b7b59b97a4e"